### ISSUE TITLE
Let's translate ALL THE THINGS!

### ISSUE THREAD

**Issue by maxogden** [nodeschool/organizers#64]
Hey @nodeschool/owners, I need your help making workshop translations better!

I've recently hosted events in Taiwan and Japan, and while we were able to come up with an okay system for [translating the main website](https://github.com/nodeschool/nodeschool.github.io#translations), we still don't have a good system for translating the workshoppers.

The current solution is to fork `learnyounode` and publish a translated version to npm called e.g. [`learnyounode-zh-tw`](https://www.npmjs.org/package/learnyounode-zh-tw) or [`learnyounode-jp`](https://www.npmjs.org/package/learnyounode-jp). 

This isn't a very good solution though as it requires forking, and that means it adds a ton of maintenance overhead. For example, if `learnyounode` gets a bugfix then that bugfix will have to get manually applied to all of the forks. That is not very nice!

Some other issues I've run in to:
- neither [`workshopper`](https://www.npmjs.org/package/workshopper) nor [`adventure`](https://www.npmjs.org/package/adventure) have built-in translation support
- Some workshoppers need to get upgraded to use the latest `workshopper`, for example `levelmeup` uses [`workshopper@0.3.1`](https://github.com/rvagg/levelmeup/blob/master/package.json#L12) but it needs to get upgraded

I'd like to propose a solution, which is to add a feature to both `workshopper` and `adventure` that adds a new menu when you first run the workshop that lets you choose your language. So when you run `learnyounode` the first time you will get a list of languages, and you select the one you want, and it sets that in config somewhere and doesn't have to ask you again (unless you specifically open up the language selection menu again by running e.g. `learnyounode language` or something).

Also we shouldn't fork anymore, we should instead just store all of the different translations in the original workshopper repository. For example, we currently have a [problems](https://github.com/rvagg/levelmeup/tree/master/problems) folder, and in both `workshopper` and `adventure` you can specify the problems path, but we should add a new feature to both of these that lets you pass in a map of multiple languages and multiple paths to problems folders in different languages, like `problems-en` and `problems-jp`.

So, I need all of your help! Here's a big TODO list. If you want to work on one of these, declare it in the comments.

### TODO for making translations awesome

- [ ] [upgrade `levelmeup` to latest `workshopper`](https://github.com/rvagg/levelmeup/issues/37)
- [x] [add multi-lang support as described above to `workshopper`](https://github.com/rvagg/learnyounode/issues/126)
- [ ] [add multi-lang support as described above to `adventure`](https://github.com/substack/adventure/issues/6)
- [ ] write a beginner friendly guide that explains how to write a new translation for both `workshopper` and `adventure` based workshops

### Other relevant discussions

- https://github.com/rvagg/workshopper/pull/51
- https://github.com/jlord/git-it/issues/62

Ideas? Feedback? Comment below!

**Comment by martinheidegger** [comment]
learnyounode and workshopper - done :dancers:

**Comment by a0viedo** [comment]
You're awesome @martinheidegger! :tada:

**Comment by mikeal** [comment]
Just wanted to let all the awesome people here know that we've kicked on localization efforts for io.js :)

Sign up here https://github.com/nodeschool/discussions

**Comment by mikeal** [comment]
Just wanted to let everyone know that we've kicked off localization efforts for io.js.

Sign up here https://github.com/iojs/website/issues/125

**Comment by tdd** [comment]
Hey guys,

Just FYI, in anticipation of our first NodeSchool Paris (at Mozilla Paris, Feb 21, filled-up and with 125% waiting list already…), I'm forking every workshopper (plus workshopper itself) and adding FR translations (and upgrading to latest workshopper when necessary).

So if anyone by sheer random chance is tackling FR just now, get in touch so we don't overlap.

**Comment by tdd** [comment]
Hey guys,

FYI, the status of g11n and FR L10n:

### Infrastructure

[x] L10n fr + g11n tweaks & upgrades on rvagg/workshopper (resulted in 2.3.1)
[x] L10n fr + g11n tweaks & upgrades on rvagg/workshopper-exercise (resulted in 2.3.0)
[x] g11n on rvagg/workshopper-boilerplate *(done, pending PR merge and npm version bump)*

### Workshops

[x] L10n fr on rvagg/learnyounode *(pending npm version bump)*
[x] L10n fr on azat-co/expressworks *(pending PR merges and npm version bump)*
[x] L10n fr + g11n upgrade on mdunisch/lololodash *(pending workshopper-boilerplate update on npm so deps are correct, then PR)*
[ ] L10n fr + g11n upgrade on stevekane/promise-it-wont-hurt *(ongoing)*

Next in line: async-you, lololodash, makemehapi, count-to-6, learn-generators, kick-off-koa and functional-javascript-workshop.

Most of this work is scheduled for this week.

Then there are plans to backport `workshopper`'s i18n infrastructure to `adventure` (so translators only need to learn one way to do things, as much as possible anyway…), which lets us L10n `javascripting` and `how-to-node`, and perhaps refactor `stream-adventure` to use the latest `adventure` so it can be L10n'd as well.

**Comment by tdd** [comment]
A comprehensive roadmap (at least a to-do list), that I'll update as I go, on the work around NodeSchool workshops and workshoppers: https://gist.github.com/tdd/d7b2b719485cdf87bd5f.

Comments welcome!

**Comment by martinheidegger** [comment]
:+1: Way cool! @tdd I am thinking that instead of translating adventure it might be better to switch materials to workshoppers it terms of constant maintenance Cost. https://github.com/sethvincent/javascripting/issues/64

**Comment by rvagg** [comment]
@martinheidegger & @tdd: two reasons that workshopper has a high barrier to entry than adventure that we can fix are:

 1. lack of docs (my fault, obviously, even though I keep on promising them ...)
 2. too much boilerplate, I know @tdd has presented a proposal to deal with this but I haven't had time to look at it but in general I agree that there are basic cases that we can make easier

Workshopper 2+ was intended to be way more flexible than the original implementation that came from stream-adventure, which I believe it is, but that flexibility introduces challenges, such as the above, but I believe they are easily addressable and am not at all married to the particular implementation and hope for it to learn and grow from continued use. While I'd like to be able to have input on the changes proposed by others I'm very willing to defer to those who have more energy and time than me to invest in making it better and currently you two are probably at that place.

**Comment by tdd** [comment]
Hey guys,

A few thoughts I have on this:

* Yes, the split `adventure` rose out of was about code architecture / codebase layout.  It's aiming to be much lighter, and entirely API-driven, where `workshopper` is more CoC-driven (even if that doesn't show much in the current exercise boilerplate).
* We can aim for reduced boilerplate, but I'm not sure at all this will convert `adventure` users. We need to discuss this with these few workshop owners once we have a solid story for `workshopper`, particularly in terms of docs and reduced boilerplate. So these "task deps" can inform the order in which we tackle the [to-do list](https://gist.github.com/tdd/d7b2b719485cdf87bd5f).
* I do agree that closing that rift, producing a single workshopper codebase, would be best wrt maintenance and getting-started paths for workshop authors and translators. The ecosystem is, right now, massively based on `workshopper`, so evolving this one to make it more palatable to users of `adventure` sounds like a good course of action.
* Rod, I'm reluctant right now to assume decisional / executive power over `workshopper` et al. for anything but tiny things. This is still very much your baby. I'd be more comfortable merging a PR when I know you don't take issue with its contents.

Specifically, as a first order of business, I'd love to merge my PR on `require('workshopper-exercise/basic')` ([reduced boilerplate for basic case](https://github.com/rvagg/workshopper-exercise/pull/18)), then go on upgrading the remaining `workshopper`-based workshops.

I would then probably migrate former workshop upgrades to the new, trivial boilerplate when applicable, and tackle the *docs* part of the to-do list, before pitching the result to `adventure`-based workshop owners, in an attempt to port these over.

Best,

**Comment by martinheidegger** [comment]
I am working on a API compatibility between workshopper & adventure https://github.com/rvagg/workshopper/pull/106 at some point I will need help testing it but it should allow easy porting of current adventures -> workshopper.

**Comment by martinheidegger** [comment]
FYI: @sethvincent just kindly merged a PR that added translation to javascripting using [workshopper-adventure](https://github.com/workshopper/workshopper-adventure)

**Comment by a0viedo** [comment]
@martinheidegger you're awesome :tada:

**Comment by tdd** [comment]
Hey @martinheidegger so lemme get this right: is `workshopper-adventure` an `adventure`-API-compatible port of `workshopper`?  To ease in the ports of `adventure`-based workshops?  Or is it something else?

At any rate: **awesomeness** :tada:, as this will allow me to contrib FR to `javascripting` very, very soon. This was the only language-related workshop that lacked FR :wink: 

Do you think this path can be take for `how-to-npm`, too? that'd be kickass!

**Comment by martinheidegger** [comment]
Its more a `branch` than a `port` really and it is already a PR at workshopper. `workshopper-adventure` is just a temporary release until we figured `workshopper` out - to test the system if you will. `how-to-npm` is a bit tricky to translate (not to port to `workshopper-adventure`). To my understanding @watilde is working on that.

**Comment by martinheidegger** [comment]
This issue has been open for too long and needs rethinking. Closing it for now.
