### ISSUE TITLE
Quality Checklist for Workshoppers

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/organizers#89]
I don't think we need to enforce it but I think it would be good to setup a checklist for workshoppers to create a similar quality level to workshoppers and other tutorials. I can imagine questions like

- [ ] Are the sections solvable by just reading the specifications or is required information hidden in the "Hints"?
- [ ] Are the files created in the sections interesting for purposes outside of the nodeschool? Do they have wit and/or practical use?
- [ ] Did someone check-read the text?
- [ ] Does the tutorial explain the relevance of the topic? (Why should someone learn it?)
- [ ] Does the tutorial have between 10 ~ 15 steps?
- [ ] Is there variance to the tests that makes sure that people don't trick the results?
- [ ] Are all the required/recommended modules added to the dependencies folder so people can use the workshopper offline?
- [ ] Is all the required documentation copied into a folder for offline use?

What do you think?

**Comment by grabbou** [comment]
That'd be cool. When i first started writing my own workshop, I've been really worried about the quality and if I do follow all the things the rest workshoppers do.

**Comment by martinheidegger** [comment]
Added issue to workshopper-adventure-test that should automate it: https://github.com/workshopper/workshopper-adventure-test/issues/29
